### ISSUE TITLE
Deprecation Warnings When Running `npm install`

### ISSUE THREAD

**Issue by ipc103** [learn-co-curriculum/js-looping-and-iteration-filter-and-map-lab#3]
Hi! A student has reported the following deprecation warnings when running `npm install` for this lab. 

```bash
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead

npm WARN deprecated text-encoding@0.6.4: no longer maintained

npm WARN deprecated express@2.5.11: express 2.x series is deprecated

npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.

npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.

npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.

npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
```

Not sure what the current strategy is/should be for updating package versions, but wanted to log this here as I imagine this could be an issue for many labs in this section.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
